### PR TITLE
Make 'ast' and 'parser' modules public

### PR DESCRIPTION
**Pull request by talliberman**
Hi Sean,

I need to access the internal modules 'ast' and 'parser' so I've added optional features to expose them.

Please let me know if you prefer to handle this in a different way.

Thanks,
Tal

### CODE REVIEW

**Comment by seanyoung** [comment]
Thanks for your PR!

I think it might make sense to unconditionally set the ast and parser modules as pub, if you need access. What exactly are you trying to do?

**Comment by talliberman** [comment]
Happy to help, thanks for being responsive!

I've updated the PR to simply make ast and parser public.

**Comment by seanyoung** [comment]
So why exactly do you want these modules to be public?

**Comment by talliberman** [comment]
I need to traverse the AST. This requires access to both modules.

**Comment by seanyoung** [comment]
Makes sense.

**Pull request merged**
